[urls]
  wsagg = "wss://fstream.binance.com/ws/"
  rest = "https://fapi.binance.com/"

[argg]
  symbol = "dashusdt"
  backtesting = 1 # for backtesting 0 false 1 true
  dgarray_file = "dgarray.bin"
  status_file = "status_code.json"

  [argg.grid] # array aggTrades
    lines = 10000 #10000 # + 8 lines headers
    cols = 4
    interval_min = 1

    bsize = 320000 #480432 # (lines + headers) * cols * bytesize (float64==8bytes)
    shm = "algo_bot_grid"

  [argg.raw]
    ac = 41  # Amount Cells
    dsib = 164  # Data size in bytes
    hsib = 4

    bsize = 8192  # 6890 (4 * 41 = 164) headers +
    # (41*164=6724) data + 2 counter status write/read
    shm = "raw_data_memory"

  [argg.sign]
    bsize = 4096
    shm = "signal_to_logic"

  [argg.debug]
    lines = 5000
    cols = 3
    multiplier = 1_000_000

    offset = 128 # for headers cols 0-64 & 64-128 other info
    bsize = 120128
    shm = "debug_array"

  [argg.status] # Module Status
    parsing = {"p"=10, "m"=0, "d"=1, "dgc"=0}
    logic = {"p"=11, "m"=2, "d"=3, "dgc"=1}
    network = {"p"=12, "m"=4, "d"=5, "dgc"=2}
    network_sim = {"p"=12, "m"=6, "d"=7, "dgc"=2}

    monitoring = 9
    main = 10

    bsize = 4096
    shm = "_status_table_"
