[urls]
  wsagg = "wss://fstream.binance.com/ws/"
  rest = "https://fapi.binance.com/"

[argg]
  symbol = "dashusdt"
  backtesting = 1 # for backtesting 0 false 1 true

  profiling_dump = "dump/profiling.bin"
  profiling_dump_csv = "dump/profiling.csv"
  pheaders_dump_csv = "dump/pheaders.csv"
  status_file = "status_code.json"
  data_path = "data/aggtrades.csv"

  [argg.grid] # array aggTrades
    lines = 10000 #10000 # + 8 lines headers
    cols = 4
    interval_min = 1

    bsize = 327680 #480432 # (lines + headers) * cols * bytesize (float64==8bytes)
    shm = "algo_bot_grid"

  [argg.profiling]
    lines = 5000
    cols = 3

    offset = 128 # for headers cols 0-64 & 64-128 other info
    bsize = 122880
    shm = "profiling_array"

  [argg.raw]
    ac = 128  # Amount Cells
    dsib = 256  # Data size in bytes
    hsib = 1
    # also in code: _sssd = -3, _ir = -2 , _iw = -1

    bsize = 40960 # 8192  # 6890 (128 * 4 = 512) headers +
    # (128 * 256 = 32768) data + 2 counter status write/read
    shm = "raw_data_memory"

  [argg.metrics]
    # grid
    base_price_and_timestamp = 0 # 0 start id , and 0 + size, example: float/int64=8, [0: 0+8+8]
    # reader
    id_y_x = 128 # +8+8
    flag_r = 144 # 1 byte
    flag_w = 145 # 1 byte
    # tools
    bsize = 4096
    shm = "signal_to_logic"

  [argg.status] # Module Status

    parsing = {"p"=10, "m"=0, "d"=1, "dgc"=0}
    logic = {"p"=11, "m"=2, "d"=3, "dgc"=1}
    network = {"p"=12, "m"=4, "d"=5, "dgc"=2}
    network_sim = {"p"=12, "m"=6, "d"=7, "dgc"=2}

    monitoring = 9
    main = 10

    bsize = 4096
    shm = "_status_table_"
